"""Example 10: Generate a video script from a story with RAG.

This example indexes one story file and asks the configured RAG pipeline to
produce a character bible, image storyboard, and 8-second transition plan.

Usage:
    python examples/10_video_script_generator.py --story-path examples/data/ho_guom_improved.txt

The script requires an LLM API key for the selected provider. Configure keys in
.env or environment variables before running.
"""

from __future__ import annotations

import argparse
import io
import sys
from pathlib import Path
from typing import Optional


def configure_console() -> None:
    """Use UTF-8 console output on Windows when running as a script."""
    if sys.platform == "win32" and hasattr(sys.stdout, "buffer"):
        sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
        sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")


PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.rag import AdvancedRAG
from src.utils.config import Config


CHARACTER_PROMPT = """Read the story context and extract a character bible.
For each important character, include:
1. Name
2. Personality and core traits
3. Story role or RPG-style class
4. Signature skills/actions
5. Detailed visual prompt for image generation
Return concise Markdown. If the story is Vietnamese, answer in Vietnamese."""

SCENE_PROMPT = """Split the story into chronological still-image storyboard frames.
For each image, include:
- Image number and short scene title
- Main plot beat
- Detailed visual prompt: characters, setting, lighting, camera angle, colors, and animation style
Return concise Markdown. If the story is Vietnamese, answer in Vietnamese."""

TRANSITION_PROMPT_TEMPLATE = """Create video transition prompts between consecutive storyboard images.
Rules:
- Each transition connects Image K to Image K+1.
- Each transition lasts exactly {seconds_per_transition} seconds.
- Video 1 starts at 00:00.
For each transition, include:
1. Video number, time range, and image pair
2. Visual motion/camera transition
3. Voiceover/dialogue fitted to the duration
4. SFX and BGM notes
Return concise Markdown. If the story is Vietnamese, answer in Vietnamese."""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate storyboard and video transition script from one story."
    )
    parser.add_argument("--story-path", required=True, help="Path to a UTF-8 story text file.")
    parser.add_argument("--output-path", default="script_output.md", help="Markdown output path.")
    parser.add_argument("--provider", default=None, help="LLM provider, e.g. openai or anthropic.")
    parser.add_argument("--model", default=None, help="LLM model name.")
    parser.add_argument("--embedding-model", default=None, help="Embedding model override.")
    parser.add_argument("--transition-seconds", type=int, default=8, help="Seconds per transition video.")
    parser.add_argument("--retrieval-k", type=int, default=6, help="Number of chunks to retrieve per prompt.")
    parser.add_argument("--enable-reranking", action="store_true", help="Enable reranking; slower on first run.")
    return parser.parse_args()


def clean_markdown_fence(text: str) -> str:
    """Remove a surrounding Markdown code fence from LLM output."""
    text = (text or "").strip()
    if text.startswith("```"):
        first_newline = text.find("\n")
        if first_newline != -1:
            text = text[first_newline + 1 :]
        if text.rstrip().endswith("```"):
            text = text.rstrip()[:-3]
    return text.strip()


def seconds_to_timestamp(seconds: int) -> str:
    """Format seconds as MM:SS."""
    minutes, remainder = divmod(max(seconds, 0), 60)
    return f"{minutes:02d}:{remainder:02d}"


def transition_time_range(index: int, seconds_per_transition: int = 8) -> str:
    """Return the time range for a 1-based transition index."""
    start = (index - 1) * seconds_per_transition
    end = index * seconds_per_transition
    return f"{seconds_to_timestamp(start)} - {seconds_to_timestamp(end)}"


def build_output(characters: str, scenes: str, transitions: str) -> str:
    """Combine generated sections into one Markdown document."""
    return f"""# Video Storyboard and Transition Script

Generated by Ultimate RAG Framework.

---

## 1. Character Bible

{characters}

---

## 2. Still-Image Storyboard

{scenes}

---

## 3. Video Transitions

{transitions}
"""


def create_rag(args: argparse.Namespace, config: Optional[Config] = None) -> AdvancedRAG:
    """Create an AdvancedRAG instance from CLI args and env config."""
    config = config or Config()
    llm_config = config.get_llm_config()
    provider = args.provider or llm_config.get("provider") or "openai"
    model = args.model or llm_config.get("model") or "gpt-4o-mini"
    api_key = llm_config.get("api_key")
    embedding_model = args.embedding_model or config.get("DEFAULT_EMBEDDING_MODEL", "BAAI/bge-m3")

    return AdvancedRAG(
        llm_provider=provider,
        llm_model=model,
        llm_api_key=api_key,
        embedding_provider=config.get("DEFAULT_EMBEDDING_PROVIDER", "huggingface"),
        embedding_model=embedding_model,
        vector_store_provider=config.get("DEFAULT_VECTOR_STORE", "faiss"),
        retrieval_k=args.retrieval_k,
        use_hybrid=True,
        use_reranking=args.enable_reranking,
        use_cache=False,
    )


def main() -> int:
    configure_console()
    args = parse_args()
    story_path = Path(args.story_path)
    if not story_path.exists():
        print(f"Story file not found: {story_path}", file=sys.stderr)
        return 1

    rag = create_rag(args)
    chunks = rag.add_documents([story_path])
    print(f"Indexed {chunks} chunks from {story_path}")

    characters = clean_markdown_fence(rag.query(CHARACTER_PROMPT))
    scenes = clean_markdown_fence(rag.query(SCENE_PROMPT))
    transitions = clean_markdown_fence(
        rag.query(TRANSITION_PROMPT_TEMPLATE.format(seconds_per_transition=args.transition_seconds))
    )

    output = build_output(characters, scenes, transitions)
    output_path = Path(args.output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(output, encoding="utf-8", newline="\n")
    print(f"Saved script to {output_path.resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
